language: go

go:
  - 1.6

before_install:
  - go get -u github.com/mitchellh/gox
  - go get -u github.com/valyala/quicktemplate/qtc

script:
  # build test for supported platforms
  - gox -os="linux"
  - gox -os="darwin"
  - gox -os="freebsd"

  # run tests on a standard platform
  - go test -v .
  - go test -v ./qtc
